apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  name: {{ .Values.database.name }}
spec:
  mariaDbRef:
    name: {{ include "iam-db.fullname" . }}
  characterSet: utf8
  collate: utf8_general_ci
